name: Build and publish Docker image

on:
  push:
    branches:
    - 'master'
    - 'github-actions'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            px4/px4-dev:latest
            ghcr.io/px4/px4-dev:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
